// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv7x0Uu4v6fUlsYa1_kgSSEUtRC0e-0Bk',
    appId: '1:882399206308:web:225536d9f9fb2924d1ff31',
    messagingSenderId: '882399206308',
    projectId: 'graduate-project-f8cdd',
    authDomain: 'graduate-project-f8cdd.firebaseapp.com',
    storageBucket: 'graduate-project-f8cdd.firebasestorage.app',
    measurementId: 'G-55VE2MDB3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe-4TgDCn9zW1JhVXuNhTG0aptCnKjF4s',
    appId: '1:882399206308:android:5f0cfb6bdea0ec7cd1ff31',
    messagingSenderId: '882399206308',
    projectId: 'graduate-project-f8cdd',
    storageBucket: 'graduate-project-f8cdd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsA2ufhlomrqXMNZCFhDguLgFt1olfJTU',
    appId: '1:882399206308:ios:71a599902c7ca09dd1ff31',
    messagingSenderId: '882399206308',
    projectId: 'graduate-project-f8cdd',
    storageBucket: 'graduate-project-f8cdd.firebasestorage.app',
    iosBundleId: 'com.example.graduateproject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsA2ufhlomrqXMNZCFhDguLgFt1olfJTU',
    appId: '1:882399206308:ios:71a599902c7ca09dd1ff31',
    messagingSenderId: '882399206308',
    projectId: 'graduate-project-f8cdd',
    storageBucket: 'graduate-project-f8cdd.firebasestorage.app',
    iosBundleId: 'com.example.graduateproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv7x0Uu4v6fUlsYa1_kgSSEUtRC0e-0Bk',
    appId: '1:882399206308:web:0ebb1ad8b32e1288d1ff31',
    messagingSenderId: '882399206308',
    projectId: 'graduate-project-f8cdd',
    authDomain: 'graduate-project-f8cdd.firebaseapp.com',
    storageBucket: 'graduate-project-f8cdd.firebasestorage.app',
    measurementId: 'G-9WP70S22DF',
  );
}
